### ISSUE TITLE
XEP-0308 Last Message Correction: Pàdé can correct message, but not see messages corrected by another instance of Pàdé

### ISSUE THREAD

**Issue by marclaporte** [igniterealtime/Pade#134] opened 2019-03-19 08:50 UTC
![2019-03-19-pade-can-correct-chat-but-not-see-corrections-from-others](https://user-images.githubusercontent.com/1004261/54592175-c85a6e00-4a66-11e9-9b73-ddb7b9bef2cd.png)

Experienced on https://wikisuite.chat/
Openfire 4.3.2

Thanks!

**Comment by marclaporte** [comment] 2019-03-19 08:52
I suspect the same issue / bug / concern leads to seeing duplicate messages in some contexts.

**Comment by deleolajide** [comment] 2019-03-19 09:07
Do you get the same effect with just Converse?

**Comment by marclaporte** [comment] 2019-03-19 09:19
Yes, I do. Oups. So I refile upstream?

**Comment by deleolajide** [comment] 2019-03-19 09:22
I suspect it is a Converse issue. Recently, a lot of work went into fixing the elusive duplicate post issue. This might have broken last message correction.

**Comment by deleolajide** [comment] 2019-03-20 12:27
I cannot reproduce this Issue. All my message corrections are corrected fine

![image](https://user-images.githubusercontent.com/110731/54684101-407a6f80-4b0b-11e9-9f1b-730bdd4a2325.png)

![image](https://user-images.githubusercontent.com/110731/54684130-52f4a900-4b0b-11e9-9e5a-34f5a2ea069d.png)

**Comment by deleolajide** [comment] 2019-04-19 15:50
I think this is now fixed with version 4.2 of converse

**Comment by deleolajide** [comment] 2019-07-10 11:55
I am now able to reproduce this issue with groupchat. It does not happen in 1to1 chat

**Comment by deleolajide** [comment] 2019-08-17 14:01
This should be fixed with version 1.3 and Openfire monitoring plugin 1.8.0

**Closed by deleolajide** 2019-08-17 14:01 UTC
