### ISSUE TITLE
Bookmarks do not save

### ISSUE THREAD

**Issue by luciash** [igniterealtime/Pade#62] opened 2018-09-24 14:20 UTC
At least it seems so. After reopening the Pade window there are no bookmarks of the groupchats; all gone :(

**Comment by deleolajide** [comment] 2018-09-25 09:06
Sorry about that. Did you save the bookmarks after you created them?  
I am unable to reproduce the issue. I have just cleared my localstorage, re-installed Pade, added/saved bookmarks, close and re-open Converse. My bookmarks are still there.

**Comment by luciash** [comment] 2018-09-26 18:43
Hmm, now it works again... interesting :)

**Comment by luciash** [comment] 2018-09-30 08:12
I suspect there is some client side caching issue... but good for now.

**Comment by marclaporte** [comment] 2018-10-11 01:45
I see this problem as well.

**Comment by marclaporte** [comment] 2018-10-11 01:49
<img width="325" alt="2018-10-10_214822" src="https://user-images.githubusercontent.com/1004261/46775703-540ce900-ccd6-11e8-9976-98a326343949.png">

**Comment by deleolajide** [comment] 2018-10-11 08:48
I can't reproduce this. here is my evidence :-)

https://wikisuite.net:7443/httpfileupload/2d3abf35-a1b4-41cf-9ff3-1bb59aeec8e3/screencast-enngimmni.webm

**Comment by marclaporte** [comment] 2018-10-14 18:00
I just installed Pàdé@Home 0.6.0 and it works!

Thanks!

**Comment by marclaporte** [comment] 2018-10-22 14:49
Just got it again
![2018-10-22_104716](https://user-images.githubusercontent.com/1004261/47299372-10748200-d5e8-11e8-8db4-a6e5484e4877.png)

**Comment by marclaporte** [comment] 2018-10-22 15:00
Guus just informed me:
Marc Laporte: bookmarking in Converse uses a newer technique than what is available in Openfire 4.2.3. It will be available in Openfire 4.3.0. Depending on what server you use (this one already uses a prerelease of 4.3.0) your mileage may vary.

**Comment by guusdk** [comment] 2018-10-22 15:45
Hmm, that stack trace does not seem to relate to the unavailability of PEP Bookmarking in 4.2.3. "Cannot Read property 'toLowerCase' of undefined" sounds as if a null-string is being operated on. @jcbrand, does this ring a bell?

**Comment by deleolajide** [comment] 2018-10-22 16:08
```
      _converse.Bookmarks = Backbone.Collection.extend({
        model: _converse.Bookmark,
        comparator: item => item.get('name').toLowerCase(),
```
For now, I am going to stick in some defensive code for when bookmark name is empty

**Comment by marclaporte** [comment] 2018-11-11 22:01
I appreciate. 

I think the offending one was this one:
http://wikisuite.org/XMPP-chatrooms#JMAP

I removed from my list for now.

**Comment by guusdk** [comment] 2018-11-12 11:47
I think this is the bug (now fixed) in Converse: https://github.com/conversejs/converse.js/issues/1158

**Comment by deleolajide** [comment] 2018-11-12 12:03
That fix is in latest Pàdé code. I think we can close this issue *again*.

**Closed by deleolajide** 2018-11-12 12:03 UTC
