### ISSUE TITLE
File uploading still not working with version 1.2.1

### ISSUE THREAD

**Issue by banderosss** [igniterealtime/Pade#159] opened 2019-04-11 02:25 UTC
File uploading now are working with version 1.2.1 in group chat, but does not work when chatting with a specific user. Also if the user is simply a member and not a moderator or owner of the room, he cannot connect to the room. OpenFire version 4.3.2, all plugins are updated to the latest versions.

**Comment by deleolajide** [comment] 2019-04-11 08:47
> but does not work when chatting with a specific user.

Aaarrgghh!!. Now fixed in version 1.2.2

>Also if the user is simply a member and not a moderator or owner of the room, he cannot connect to the room

![image](https://user-images.githubusercontent.com/110731/55943466-8c1dc600-5c3e-11e9-9704-2656441ac368.png)

Sorry, I cannot reproduce this

**Comment by banderosss** [comment] 2019-04-12 02:02
![Owner_Moderator](https://user-images.githubusercontent.com/49503733/56006872-ecce0100-5d19-11e9-8648-fc4817eac771.png)

In this case it's ok

![Member](https://user-images.githubusercontent.com/49503733/56006914-1a1aaf00-5d1a-11e9-859f-37981c65212e.png)

When the user is just a member, there are no errors, but the chat does not work.

![Presence](https://user-images.githubusercontent.com/49503733/56007062-b644b600-5d1a-11e9-9b05-a5bd9ef2368f.png)
I noticed a feature, if in the server settings the option "Broadcast Presence for" is marked only for moderators, then the chat does not work. And if it marked for moderators and participants, the chat works.

**Comment by deleolajide** [comment] 2019-04-13 16:55
Converse needs the room presence broadcasts in order to work. If this is still an issue for you, please raise an issue at https://github.com/conversejs/converse.js/issues.

**Closed** 2019-04-13 16:56 UTC
Labels: bug
