### ISSUE TITLE
Markdown Editor Errors

### ISSUE THREAD

**Issue by AGNaumov** [igniterealtime/Pade#160] opened 2019-04-12 01:11 UTC
- В версии 1.2.2. Не работает отправка сообщений через Markdown Editor.
- Некорректно отображается нумерованный список 

Google translation by translator:

- In version 1.2.2. Sending messages through the Markdown Editor does not work.
- Incorrectly numbered list is displayed

**Comment by deleolajide** [comment] 2019-04-13 16:58
> * In version 1.2.2. Sending messages through the Markdown Editor does not work.

Fixed in version 1.2.3

**Comment by deleolajide** [comment] 2019-04-13 17:01
> * Incorrectly numbered list is displayed

I am not able to reproduce this. I always get a numbered list

![image](https://user-images.githubusercontent.com/110731/56082873-094f6380-5e16-11e9-9471-06b7fc8abb6f.png)

**Comment by deleolajide** [comment] 2019-04-13 21:40
There is an outstanding issue with the openfire monitoring plugin that removes \n in message text and causes markup to display incorrectly when chat history is shown. See https://github.com/igniterealtime/openfire-monitoring-plugin/issues/36

**Closed** 2019-06-14 08:54 UTC
